2019-07-09 21:17:48,175 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-09 21:20:06,572 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-09 21:22:52,814 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-09 21:30:41,333 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-09 21:33:39,293 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-09 21:37:27,115 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-09 21:54:21,598 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 07:16:12,442 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 07:22:26,056 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 07:29:33,385 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 07:34:01,828 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 07:49:05,168 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 08:17:26,157 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 08:24:42,937 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 09:22:32,131 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 09:49:22,017 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 09:57:22,646 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 10:03:02,761 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 10:17:09,325 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 10:20:39,950 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 10:21:35,969 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 10:38:33,187 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 10:39:08,871 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 10:41:34,414 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 10:42:32,526 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 10:58:24,960 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 11:00:03,617 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 11:04:49,412 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 11:04:52,852 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 11:04:54,587 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 11:07:37,034 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 11:08:45,095 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 11:19:49,316 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 11:24:40,099 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 11:42:20,320 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 11:56:30,352 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 11:56:58,381 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 11:58:46,366 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 12:13:20,185 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 12:19:42,779 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 12:26:45,657 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 19:41:58,352 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 19:46:33,435 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 19:57:53,165 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 20:11:03,055 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-10 20:27:57,460 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-11 07:57:33,264 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-11 08:04:44,700 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-11 08:10:40,508 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-11 08:19:06,102 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-11 10:30:21,127 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-11 10:43:39,143 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-11 10:57:52,037 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-11 11:08:02,339 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-11 11:20:55,056 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-11 12:22:14,221 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-11 12:22:21,062 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-11 12:26:15,446 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-11 12:28:37,942 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-11 14:26:40,266 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-11 14:35:10,659 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:223] - ERROR: 向定时查询节点发送域名数据失败0/3
2019-07-11 14:35:10,662 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:223] - ERROR: 向定时查询节点发送域名数据失败1/3
2019-07-11 14:35:10,664 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:223] - ERROR: 向定时查询节点发送域名数据失败2/3
2019-07-11 14:38:32,037 - /Users/mrcheng/OneDrive - stu.hit.edu.cn/Projects/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - INFO: 对方接收域名ns结果文件成功
2019-07-16 09:40:08,676 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:85] - INFO: 对方接收域名ns结果文件成功
2019-07-16 09:40:17,894 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:85] - INFO: 对方接收域名ns结果文件成功
2019-07-16 09:40:27,850 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:85] - INFO: 对方接收域名ns结果文件成功
2019-07-16 09:42:32,524 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:85] - INFO: 对方接收域名ns结果文件成功
2019-07-16 09:44:27,791 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:85] - INFO: 对方接收域名ns结果文件成功
2019-07-16 09:46:27,248 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:85] - INFO: 对方接收域名ns结果文件成功
2019-07-16 09:48:25,403 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:85] - INFO: 对方接收域名ns结果文件成功
2019-07-16 09:48:33,473 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:85] - INFO: 对方接收域名ns结果文件成功
2019-07-16 09:50:23,494 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:85] - INFO: 对方接收域名ns结果文件成功
2019-07-16 09:52:18,956 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:85] - INFO: 对方接收域名ns结果文件成功
2019-07-16 09:52:26,075 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:85] - INFO: 对方接收域名ns结果文件成功
2019-07-16 09:53:35,631 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:85] - INFO: 对方接收域名ns结果文件成功
2019-07-16 09:54:22,629 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:85] - INFO: 对方接收域名ns结果文件成功
2019-07-16 09:57:23,676 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 09:59:20,085 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 09:59:30,389 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 09:59:40,053 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 10:00:22,199 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 10:00:35,030 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 10:00:38,496 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 10:01:41,743 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 10:01:51,920 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 10:02:00,474 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 10:03:57,153 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 10:06:02,553 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 10:06:12,756 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 10:06:22,839 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 10:08:26,692 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 10:08:35,156 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 10:09:49,732 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 10:11:52,406 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 10:13:51,382 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 10:15:48,334 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 10:17:47,226 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 10:19:49,287 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 11:00:27,071 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - ERROR: 向对方发送域名ns结果文件失败:Timeout during request
2019-07-16 11:00:37,078 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - ERROR: 向对方发送域名ns结果文件失败:Timeout during request
2019-07-16 11:00:47,094 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - ERROR: 向对方发送域名ns结果文件失败:Timeout during request
2019-07-16 11:32:37,637 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 11:34:51,895 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 11:37:51,909 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 11:40:27,846 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：Timeout during request
2019-07-16 11:43:10,889 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 11:44:09,316 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 11:45:11,607 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 11:46:08,797 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 11:46:40,441 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 11:47:09,691 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 11:48:09,682 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 11:49:11,744 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 11:50:04,946 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 11:51:11,076 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 11:52:12,948 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 11:53:15,325 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 11:54:12,114 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 11:54:58,930 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:195] - ERROR: 向实时查询节点发送域名数据失败0/3
2019-07-16 11:54:58,930 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:195] - ERROR: 向实时查询节点发送域名数据失败1/3
2019-07-16 11:54:58,931 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:195] - ERROR: 向实时查询节点发送域名数据失败2/3
2019-07-16 11:55:58,926 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:195] - ERROR: 向实时查询节点发送域名数据失败0/3
2019-07-16 11:55:58,926 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:195] - ERROR: 向实时查询节点发送域名数据失败1/3
2019-07-16 11:55:58,927 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:195] - ERROR: 向实时查询节点发送域名数据失败2/3
2019-07-16 11:56:58,933 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:195] - ERROR: 向实时查询节点发送域名数据失败0/3
2019-07-16 11:56:58,934 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:195] - ERROR: 向实时查询节点发送域名数据失败1/3
2019-07-16 11:56:58,934 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:195] - ERROR: 向实时查询节点发送域名数据失败2/3
2019-07-16 11:58:08,527 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 11:59:11,797 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:00:13,011 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:01:15,487 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:02:13,448 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:02:30,339 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:03:06,836 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:04:09,844 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:05:06,608 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:06:07,957 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:07:09,520 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:08:07,902 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:09:12,565 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:10:09,638 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:11:07,087 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:12:08,570 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:13:10,719 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:14:10,659 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:15:08,448 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:16:09,445 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:17:04,865 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:18:20,141 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:19:15,585 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:20:09,416 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:21:07,761 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:22:13,664 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:23:06,841 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:24:14,400 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:25:11,337 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:26:11,368 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:27:11,417 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:28:11,427 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:29:08,376 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:30:11,658 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:31:17,206 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:32:14,116 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:33:08,520 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:34:16,287 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:35:14,272 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:36:19,159 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:37:11,332 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:38:14,412 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:39:14,279 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:40:14,340 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:41:17,100 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:42:11,393 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:43:11,482 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:44:17,193 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:45:16,155 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:46:17,348 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:47:08,500 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:48:11,350 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:49:13,103 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:50:08,552 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:51:11,238 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:52:18,937 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:53:14,335 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:54:20,115 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:55:11,595 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:56:14,482 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:57:11,659 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:58:14,507 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 12:59:11,490 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 13:00:17,421 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 13:01:14,634 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 13:02:17,388 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 13:03:13,399 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 13:04:16,503 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 13:05:17,348 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 13:06:16,417 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 13:07:11,706 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 13:08:15,414 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 13:09:16,455 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 13:10:13,148 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 13:11:14,622 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 13:12:13,629 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 13:13:16,601 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 13:14:08,593 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 13:15:11,739 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 13:16:10,439 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 13:17:00,113 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：[Errno -2] Name or service not known
2019-07-16 13:18:01,690 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：[Errno -2] Name or service not known
2019-07-16 13:18:59,427 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：[Errno -2] Name or service not known
2019-07-16 13:19:58,973 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：[Errno -2] Name or service not known
2019-07-16 13:20:11,276 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 13:23:11,908 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 13:23:12,781 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 13:26:33,449 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:86] - ERROR: 向对方发送域名ns结果文件失败:[Errno 111] Connection refused
2019-07-16 13:29:12,553 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 13:30:11,391 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 13:37:19,589 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 13:38:18,242 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 13:40:19,379 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 13:42:18,504 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:90] - INFO: 对方接收域名ns结果文件成功
2019-07-16 13:44:20,989 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:87] - INFO: 对方接收域名ns结果文件成功
2019-07-16 13:54:14,758 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:93] - ERROR: 向对方发送域名ns结果文件失败:1/3 [Errno 111] Connection refused
2019-07-16 13:54:14,804 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:93] - ERROR: 向对方发送域名ns结果文件失败:2/3 [Errno 111] Connection refused
2019-07-16 13:54:14,849 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:93] - ERROR: 向对方发送域名ns结果文件失败:3/3 [Errno 111] Connection refused
2019-07-16 13:57:22,072 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:87] - INFO: 对方接收域名ns结果文件成功
2019-07-16 13:58:18,186 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:87] - INFO: 对方接收域名ns结果文件成功
2019-07-16 13:59:18,373 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:87] - INFO: 对方接收域名ns结果文件成功
2019-07-16 14:00:19,971 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:87] - INFO: 对方接收域名ns结果文件成功
2019-07-16 14:01:20,964 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:87] - INFO: 对方接收域名ns结果文件成功
2019-07-16 14:02:18,667 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:87] - INFO: 对方接收域名ns结果文件成功
2019-07-16 14:03:20,933 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:87] - INFO: 对方接收域名ns结果文件成功
2019-07-16 14:04:22,299 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:87] - INFO: 对方接收域名ns结果文件成功
2019-07-16 14:05:21,234 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:87] - INFO: 对方接收域名ns结果文件成功
2019-07-16 14:06:18,713 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:87] - INFO: 对方接收域名ns结果文件成功
2019-07-16 14:07:15,908 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:87] - INFO: 对方接收域名ns结果文件成功
2019-07-16 14:20:46,308 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:87] - INFO: 对方接收域名ns结果文件成功
2019-07-16 14:37:11,860 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:93] - ERROR: 向对方发送域名ns结果文件失败:1/3 [Errno 111] Connection refused
2019-07-16 14:37:11,905 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:93] - ERROR: 向对方发送域名ns结果文件失败:2/3 [Errno 111] Connection refused
2019-07-16 14:37:11,951 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:93] - ERROR: 向对方发送域名ns结果文件失败:3/3 [Errno 111] Connection refused
2019-07-16 14:49:12,758 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:87] - INFO: 对方接收域名ns结果文件成功
2019-07-16 14:52:54,459 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:87] - INFO: 对方接收域名ns结果文件成功
2019-07-16 14:54:47,808 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:87] - INFO: 对方接收域名ns结果文件成功
2019-07-16 14:58:10,198 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：Connection closed
2019-07-16 14:59:55,692 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：Connection closed
2019-07-16 15:01:28,867 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:87] - INFO: 对方接收域名ns结果文件成功
2019-07-16 15:01:51,751 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：Connection closed
2019-07-16 15:03:45,532 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：Connection closed
2019-07-16 15:05:45,679 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：Connection closed
2019-07-16 15:08:04,015 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：Connection closed
2019-07-16 15:09:50,467 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：Connection closed
2019-07-16 15:11:42,822 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：Connection closed
2019-07-16 15:13:43,458 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：Connection closed
2019-07-16 15:15:43,434 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：Connection closed
2019-07-16 15:17:45,580 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：Connection closed
2019-07-16 15:19:48,009 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：Connection closed
2019-07-16 15:22:43,593 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：Connection closed
2019-07-16 15:24:46,854 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：Connection closed
2019-07-16 15:31:51,289 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：Connection closed
2019-07-16 15:42:20,477 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：Connection closed
2019-07-16 15:58:48,055 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-16 16:00:04,353 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-16 16:02:50,641 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-16 16:03:17,195 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-16 16:04:19,353 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:93] - ERROR: 向对方发送域名ns结果文件失败:1/3 [Errno 111] Connection refused
2019-07-16 16:04:19,399 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:93] - ERROR: 向对方发送域名ns结果文件失败:2/3 [Errno 111] Connection refused
2019-07-16 16:04:19,446 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:93] - ERROR: 向对方发送域名ns结果文件失败:3/3 [Errno 111] Connection refused
2019-07-16 16:15:07,611 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-16 16:18:08,908 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-16 16:23:42,427 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-16 16:26:40,353 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-16 16:36:18,543 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-16 16:36:57,305 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-16 16:39:01,680 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-16 16:41:40,830 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-16 16:44:59,547 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-16 16:48:58,590 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-16 16:51:22,888 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-16 16:52:32,083 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-16 16:53:19,664 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:207] - ERROR: 向实时查询节点发送域名数据失败0/3
2019-07-16 16:53:24,578 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:207] - ERROR: 向实时查询节点发送域名数据失败1/3
2019-07-16 16:53:29,199 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:207] - ERROR: 向实时查询节点发送域名数据失败2/3
2019-07-16 16:54:08,670 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-16 16:54:56,598 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-16 16:55:14,821 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-16 16:56:01,572 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:207] - ERROR: 向实时查询节点发送域名数据失败0/3
2019-07-16 16:56:06,387 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:207] - ERROR: 向实时查询节点发送域名数据失败1/3
2019-07-16 16:56:11,075 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:207] - ERROR: 向实时查询节点发送域名数据失败2/3
2019-07-16 16:58:04,937 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-16 16:59:40,367 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:207] - ERROR: 向实时查询节点发送域名数据失败0/3
2019-07-16 16:59:44,773 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:207] - ERROR: 向实时查询节点发送域名数据失败1/3
2019-07-16 16:59:49,137 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:207] - ERROR: 向实时查询节点发送域名数据失败2/3
2019-07-16 17:00:54,141 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-16 17:01:40,348 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:209] - ERROR: 向实时查询节点发送域名数据失败0/3
2019-07-16 17:01:44,887 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:209] - ERROR: 向实时查询节点发送域名数据失败1/3
2019-07-16 17:01:49,421 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:209] - ERROR: 向实时查询节点发送域名数据失败2/3
2019-07-16 17:02:24,100 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-16 17:03:10,543 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:209] - ERROR: 向实时查询节点发送域名数据失败0/3
2019-07-16 17:03:14,939 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:209] - ERROR: 向实时查询节点发送域名数据失败1/3
2019-07-16 17:03:19,263 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:209] - ERROR: 向实时查询节点发送域名数据失败2/3
2019-07-16 17:04:16,361 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-16 17:04:23,998 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:209] - ERROR: 向实时查询节点发送域名数据失败0/3
2019-07-16 17:04:24,680 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:209] - ERROR: 向实时查询节点发送域名数据失败1/3
2019-07-16 17:04:25,361 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:209] - ERROR: 向实时查询节点发送域名数据失败2/3
2019-07-16 17:06:00,804 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-16 17:08:10,631 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:209] - ERROR: 向实时查询节点发送域名数据失败0/3
2019-07-16 17:08:15,169 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:209] - ERROR: 向实时查询节点发送域名数据失败1/3
2019-07-16 17:08:19,695 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-16 17:08:23,460 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:209] - ERROR: 向实时查询节点发送域名数据失败2/3
2019-07-16 17:09:50,177 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:87] - INFO: 对方接收域名ns结果文件成功
2019-07-16 17:10:46,147 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-16 17:12:53,303 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:209] - ERROR: 向实时查询节点发送域名数据失败0/3
2019-07-16 17:12:57,683 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:209] - ERROR: 向实时查询节点发送域名数据失败1/3
2019-07-16 17:13:02,149 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-16 17:13:05,942 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:209] - ERROR: 向实时查询节点发送域名数据失败2/3
2019-07-16 17:14:59,096 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-16 17:17:05,766 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:209] - ERROR: 向实时查询节点发送域名数据失败0/3
2019-07-16 17:17:10,242 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:209] - ERROR: 向实时查询节点发送域名数据失败1/3
2019-07-16 17:17:14,499 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:209] - ERROR: 向实时查询节点发送域名数据失败2/3
2019-07-16 17:20:06,314 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-16 17:21:57,392 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:209] - ERROR: 向实时查询节点发送域名数据失败0/3
2019-07-16 17:22:02,453 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:209] - ERROR: 向实时查询节点发送域名数据失败1/3
2019-07-16 17:22:19,784 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-16 17:24:07,857 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-16 17:25:41,201 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:209] - ERROR: 向实时查询节点发送域名数据失败0/3
2019-07-16 17:25:45,611 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:209] - ERROR: 向实时查询节点发送域名数据失败1/3
2019-07-16 17:25:49,892 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:209] - ERROR: 向实时查询节点发送域名数据失败2/3
2019-07-16 17:27:41,149 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-16 17:29:34,022 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:209] - ERROR: 向实时查询节点发送域名数据失败0/3
2019-07-16 17:29:38,673 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:209] - ERROR: 向实时查询节点发送域名数据失败1/3
2019-07-16 17:29:43,328 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:209] - ERROR: 向实时查询节点发送域名数据失败2/3
2019-07-16 17:31:41,943 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-16 17:34:35,617 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：unbound method fetch() must be called with AsyncHTTPClient instance as first argument (got unicode instance instead)
2019-07-16 17:34:44,948 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：unbound method fetch() must be called with AsyncHTTPClient instance as first argument (got unicode instance instead)
2019-07-16 17:36:29,917 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：unbound method fetch() must be called with AsyncHTTPClient instance as first argument (got unicode instance instead)
2019-07-16 17:38:16,710 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：Connection closed
2019-07-16 17:41:01,533 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：Connection closed
2019-07-16 17:41:47,222 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-16 17:43:42,810 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：Connection closed
2019-07-16 17:46:49,836 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：Connection closed
2019-07-16 17:51:51,301 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-16 17:52:44,162 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-16 17:52:57,326 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：Connection closed
2019-07-16 17:55:42,733 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：Connection closed
2019-07-16 17:58:44,904 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：Connection closed
2019-07-17 08:36:34,185 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-17 08:37:23,316 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:195] - ERROR: 向实时查询节点发送域名数据失败0/3
2019-07-17 08:37:23,473 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:195] - ERROR: 向实时查询节点发送域名数据失败1/3
2019-07-17 08:37:23,615 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:195] - ERROR: 向实时查询节点发送域名数据失败2/3
2019-07-17 08:41:10,701 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:195] - ERROR: 向实时查询节点发送域名数据失败0/3
2019-07-17 08:41:10,864 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:195] - ERROR: 向实时查询节点发送域名数据失败1/3
2019-07-17 08:41:11,024 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:195] - ERROR: 向实时查询节点发送域名数据失败2/3
2019-07-17 08:42:27,354 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:195] - ERROR: 向实时查询节点发送域名数据失败0/3
2019-07-17 08:42:27,491 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:195] - ERROR: 向实时查询节点发送域名数据失败1/3
2019-07-17 08:42:27,624 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:195] - ERROR: 向实时查询节点发送域名数据失败2/3
2019-07-17 08:44:45,977 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:227] - ERROR: 向定时查询节点发送域名数据失败0/3
2019-07-17 08:44:46,118 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:227] - ERROR: 向定时查询节点发送域名数据失败1/3
2019-07-17 08:44:46,257 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:227] - ERROR: 向定时查询节点发送域名数据失败2/3
2019-07-17 08:50:10,003 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-17 08:52:48,386 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-17 08:52:56,728 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-17 08:56:34,041 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-17 08:58:31,096 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-17 08:59:26,304 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-17 09:03:35,551 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:132] - ERROR: 获取要探测的域名失败：i
2019-07-17 09:40:27,770 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:170] - ERROR: 向实时查询节点发送域名数据失败0/3
2019-07-17 09:40:27,773 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:170] - ERROR: 向实时查询节点发送域名数据失败1/3
2019-07-17 09:40:27,776 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:170] - ERROR: 向实时查询节点发送域名数据失败2/3
2019-07-17 09:41:29,608 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:171] - ERROR: 向实时查询节点发送域名数据失败0/3
2019-07-17 09:41:29,611 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:171] - ERROR: 向实时查询节点发送域名数据失败1/3
2019-07-17 09:41:29,614 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:171] - ERROR: 向实时查询节点发送域名数据失败2/3
2019-07-17 09:45:11,009 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:89] - ERROR: 向对方发送域名dns结果文件失败:1/3 {u'code': 1}
2019-07-17 09:45:11,628 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:89] - ERROR: 向对方发送域名dns结果文件失败:2/3 {u'code': 1}
2019-07-17 09:45:12,315 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:89] - ERROR: 向对方发送域名dns结果文件失败:3/3 {u'code': 1}
2019-07-17 09:49:33,696 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:89] - ERROR: 向对方发送域名dns结果文件失败:1/3 {u'code': 1}
2019-07-17 09:49:34,564 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:89] - ERROR: 向对方发送域名dns结果文件失败:2/3 {u'code': 1}
2019-07-17 09:49:35,572 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:89] - ERROR: 向对方发送域名dns结果文件失败:3/3 {u'code': 1}
2019-07-17 10:10:08,468 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:89] - ERROR: 向对方发送域名dns结果文件失败:1/3 [Errno 111] Connection refused
2019-07-17 10:10:08,473 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:89] - ERROR: 向对方发送域名dns结果文件失败:2/3 [Errno 111] Connection refused
2019-07-17 10:10:08,476 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:89] - ERROR: 向对方发送域名dns结果文件失败:3/3 [Errno 111] Connection refused
2019-07-17 10:27:09,090 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:83] - INFO: 对方接收域名dns结果文件成功
2019-07-17 10:33:12,980 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:83] - INFO: 对方接收域名dns结果文件成功
2019-07-17 10:38:51,006 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:83] - INFO: 对方接收域名dns结果文件成功
2019-07-17 10:42:50,695 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:83] - INFO: 对方接收域名dns结果文件成功
2019-07-17 10:49:08,888 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:83] - INFO: 对方接收域名dns结果文件成功
2019-07-17 10:53:32,301 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:83] - INFO: 对方接收域名dns结果文件成功
2019-07-17 10:57:10,307 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:83] - INFO: 对方接收域名dns结果文件成功
2019-07-17 11:02:39,725 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:83] - INFO: 对方接收域名dns结果文件成功
2019-07-17 11:07:52,921 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:83] - INFO: 对方接收域名dns结果文件成功
2019-07-17 11:12:33,264 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:83] - INFO: 对方接收域名dns结果文件成功
2019-07-17 11:17:59,021 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:83] - INFO: 对方接收域名dns结果文件成功
2019-07-17 11:20:28,551 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:170] - ERROR: 向实时查询节点发送域名数据失败0/3
2019-07-17 11:20:28,554 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:170] - ERROR: 向实时查询节点发送域名数据失败1/3
2019-07-17 11:20:28,557 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:170] - ERROR: 向实时查询节点发送域名数据失败2/3
2019-07-17 11:25:33,525 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:83] - INFO: 对方接收域名dns结果文件成功
2019-07-17 11:30:41,717 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:83] - INFO: 对方接收域名dns结果文件成功
2019-07-17 11:34:39,792 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:83] - INFO: 对方接收域名dns结果文件成功
2019-07-17 11:38:11,727 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:83] - INFO: 对方接收域名dns结果文件成功
2019-07-17 12:07:33,162 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:83] - INFO: 对方接收域名dns结果文件成功
2019-07-17 12:15:35,463 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:170] - ERROR: 向实时查询节点发送域名数据失败0/3
2019-07-17 12:19:05,579 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:170] - ERROR: 向实时查询节点发送域名数据失败1/3
2019-07-17 12:21:11,273 - /dns_data/DNS_LAB/obtaining_domain_valid_dns_asyn/http_server/manage_data_handler.py[line:170] - ERROR: 向实时查询节点发送域名数据失败2/3
